insert into USERR(EMAIL)
values ('maks.m@gmail.com'),
       ('john.elton@gmail.com'),
       ('jon.smith@gmail.com'),
       ('mike.tyson@gmail.com'),
       ('emily.links@gmail.com'),
       ('alexander.brown@gmail.com'),
       ('jessica.mercedes@gmail.com'),
       ('daniel.geszp@gmail.com'),
       ('olivia.rodrigo@gmail.com'),
       ('ryans.reynold@gmail.com'),
       ('natalie.hall@gmail.com'),
       ('haggendans.miller@gmail.com'),
       ('hanna.montanna@gmail.com'),
       ('jacob.lmao@gmail.com'),
       ('madison.beer@gmail.com'),
       ('matthew.jenkins@gmail.com'),
       ('emma.claw@gmail.com'),
       ('jeronimo.stilton@gmail.com'),
       ('ava.bridget@gmail.com'),
       ('nathnaiel.cartridge@gmail.com'),
       ('maria.mario@gmail.com');